import { mkdir, realpath, unlink } from "node:fs/promises";
import { basename, dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { buildProjectGraph } from "../graph/build.ts";
import { runChecks } from "../checks/run.ts";
import { effectiveRigor } from "../checks/rigor.ts";
import type { Diagnostic } from "../diagnostics.ts";
import { WorkflowStateStore, type WorkflowActivity, type WorkflowEvent, type WorkflowRun } from "./state-store.ts";
import { buildContractContext, contractStaleness, evidenceSatisfaction } from "./projections.ts";
import type { ProjectGraph } from "../graph/project-graph.ts";

export type WorkflowGate = "specification"|"build-contract"|"verification";
export interface WorkflowBlocker { code:string; message:string; entityId?:string; artifactPath?:string }
export interface WorkflowAction { id:string; kind:string; label:string; eligible:boolean; requiredInputs:string[]; expectedOutputs:string[]; target:{entityId?:string;entityType?:string;artifactPath?:string}; blockers:WorkflowBlocker[] }
export interface GateAssessment { gate:WorkflowGate; required:boolean; eligible:boolean; approved:boolean; fingerprint:string; blockers:WorkflowBlocker[] }
export type CompletionClaimState = "addressed"|"needs-verification"|"not-addressed";
export interface ImplementationCompletionClaim {
  summary?:string;
  claims?:{
    requirements?:Array<{id:string;state:CompletionClaimState}>;
    acceptanceCriteria?:Array<{id:string;state:CompletionClaimState}>;
    lockedDecisions?:Array<{id:string;state:"respected"|"conflict"|"needs-verification"}>;
  };
  knownGaps?:string[];
  changedFiles?:string[];
}
export interface ImplementationRetryContext {
  taskId:string; implementationAttemptId:string; failedVerifications:string[]; affectedAcceptanceCriteria:string[]; affectedRequirements:string[];
  blockingFindings:string[]; knownGaps:string[]; contractId?:string; contractCurrent:boolean; nextEligibleAction:"implementation-handoff";
}
export interface ImplementationAttemptAssessment { id:string; taskId:string; attempt:number; contractId?:string; returned:boolean; claim?:ImplementationCompletionClaim; retryContext?:ImplementationRetryContext }
export interface WorkflowAssessment {
  featureId:string; repositoryValid:boolean; diagnostics:Diagnostic[]; featureDiagnostics:Diagnostic[]; blockingQuestions:string[];
  tasks:Array<{id:string;lifecycle:string;artifactPath:string;contract?:string;contractArtifactPath?:string;contractStale?:boolean;changedInputs:Array<{id:string;reason:string}>;handoffEligible:boolean}>;
  verifications:Array<{id:string;artifactPath:string;satisfied:boolean;status:string;evidenceIds:string[];missingComplements:string[]}>;
  gates:Record<WorkflowGate,GateAssessment>; actions:WorkflowAction[]; governingChanges:Array<{contractId:string;inputs:Array<{id:string;reason:string}>}>;
  implementation:{attempts:ImplementationAttemptAssessment[];pendingReturns:Array<{taskId:string;implementationAttemptId:string;claim:ImplementationCompletionClaim;verificationIds?:string[]}>;retryContexts:ImplementationRetryContext[]};
  reconciliation:{required:boolean;reasons:WorkflowBlocker[];baselineFingerprint?:string}; specificationEligible:boolean; buildContractEligible:boolean; completionEligible:boolean; fingerprint:string;
}

function blocker(code:string,message:string,entityId?:string,artifactPath?:string):WorkflowBlocker{return {code,message,...(entityId?{entityId}:{}),...(artifactPath?{artifactPath}:{})};}
function fingerprint(value:unknown):string{return Bun.hash(JSON.stringify(value)).toString(16);}
function gateSemanticFingerprint(entity:import("../domain/entities.ts").Entity|undefined){if(!entity)return "missing";const {source:_source,lifecycle:_lifecycle,...semantic}=entity;return fingerprint(semantic);}
function isWithin(root:string,target:string){const child=relative(root,target);return child!==""&&child!==".."&&!child.startsWith(`..${sep}`)&&!isAbsolute(child);}
function eventPayload<T>(event:WorkflowEvent):T{return event.payload as T;}
function implementationProjection(events:WorkflowEvent[]):WorkflowAssessment["implementation"] {
  const routeKinds=new Set(["verification-returned-to-implementation","verification-reconciliation-required","implementation-verification-satisfactory"]);
  const attempts:ImplementationAttemptAssessment[]=[];const pending=new Map<string,{taskId:string;implementationAttemptId:string;claim:ImplementationCompletionClaim}>();const retries:ImplementationRetryContext[]=[];
  for(const event of events){
    if(event.kind==="implementation-handed-off"){const value=eventPayload<{taskId:string;contractId?:string;implementationAttemptId?:string;attemptNumber?:number;retryContext?:ImplementationRetryContext}>(event);const id=value.implementationAttemptId??event.id;attempts.push({id,taskId:value.taskId,attempt:value.attemptNumber??attempts.filter(item=>item.taskId===value.taskId).length+1,contractId:value.contractId,returned:false,retryContext:value.retryContext});continue;}
    if(event.kind==="implementation-returned"){const value=eventPayload<{taskId:string;implementationAttemptId?:string;claim:ImplementationCompletionClaim|string}>(event);const target=value.implementationAttemptId?attempts.find(item=>item.id===value.implementationAttemptId):[...attempts].reverse().find(item=>item.taskId===value.taskId&&!item.returned);const implementationAttemptId=value.implementationAttemptId??target?.id??event.id;const claim=typeof value.claim==="string"?{summary:value.claim}:value.claim;if(target){target.returned=true;target.claim=claim;}pending.set(implementationAttemptId,{taskId:value.taskId,implementationAttemptId,claim});continue;}
    if(routeKinds.has(event.kind)){const value=eventPayload<{implementationAttemptId?:string}>(event);if(value.implementationAttemptId)pending.delete(value.implementationAttemptId);if(event.kind==="verification-returned-to-implementation")retries.push(eventPayload<ImplementationRetryContext>(event));continue;}
    if(event.kind==="reconciliation-complete")pending.clear();
  }
  const consumed=new Set(attempts.flatMap(item=>item.retryContext?[item.retryContext.implementationAttemptId]:[]));return {attempts,pendingReturns:[...pending.values()],retryContexts:retries.filter(context=>!consumed.has(context.implementationAttemptId))};
}
function affectedObligations(graph:ProjectGraph,taskId:string,verificationIds:string[]) {
  const taskRequirements=new Set(graph.outgoingRelationships(taskId).filter(r=>r.type==="implements").map(r=>r.to));
  const acceptanceCriteria=[...new Set(verificationIds.flatMap(id=>graph.outgoingRelationships(id).filter(r=>r.type==="verifies").map(r=>r.to)))].filter(id=>graph.incomingRelationships(id).some(r=>r.type==="has-acceptance-criterion"&&taskRequirements.has(r.from))).sort();
  const requirements=[...new Set(acceptanceCriteria.flatMap(id=>graph.incomingRelationships(id).filter(r=>r.type==="has-acceptance-criterion"&&taskRequirements.has(r.from)).map(r=>r.from)))].sort();
  return {acceptanceCriteria,requirements};
}

export function requiredVerificationsForFeature(graph: ProjectGraph, featureId: string): string[] {
  const requirements = graph.outgoingRelationships(featureId).filter(r=>r.type==="addresses").map(r=>r.to);
  const criteria = new Set(requirements.flatMap(id=>graph.outgoingRelationships(id).filter(r=>r.type==="has-acceptance-criterion").map(r=>r.to)));
  return graph.entitiesOfType("verification").filter(v=>v.required&&graph.outgoingRelationships(v.id).some(r=>r.type==="verifies"&&criteria.has(r.to))).map(v=>v.id).sort();
}

export class WorkflowCoordinator {
  private constructor(readonly repoRoot: string, readonly state: WorkflowStateStore) {}
  static async open(repoRoot: string) { await mkdir(`${repoRoot}/.lengthwise`, { recursive: true }); return new WorkflowCoordinator(repoRoot, new WorkflowStateStore(`${repoRoot}/.lengthwise/state.db`)); }

  async start(featureId: string): Promise<WorkflowRun> {
    const assessment = await this.assess(featureId); if (!assessment.repositoryValid) throw new Error("Repository cannot currently build");
    const built=await buildProjectGraph(this.repoRoot);const feature=built.ok?built.graph.getEntity(featureId):undefined;if(!feature||feature.type!=="feature")throw new Error(`Unknown feature ${featureId}`);if(feature.lifecycle==="complete")throw new Error(`Feature ${featureId} is complete; reopen it to active before starting another workflow run`);
    const run=this.state.start(featureId,"specify"); this.state.recordBaseline(run.id,assessment.fingerprint,assessment); return run;
  }
  async startFromIdea(input:{idea:string;title:string;destination:string;featureId?:string;significance?:"S"|"M"|"L"|"XL"}) {
    if(!input.idea.trim()||!input.title.trim()) throw new Error("Idea and title are required");
    const built=await buildProjectGraph(this.repoRoot); if(!built.ok) throw new Error("Repository cannot currently build");
    const path=input.destination; if(isAbsolute(path)||(!path.endsWith(".yaml")&&!path.endsWith(".yml")&&!path.endsWith(".md"))) throw new Error("Feature destination must be a relative YAML or Markdown artifact path");
    const root=await realpath(this.repoRoot); const lexicalTarget=resolve(root,path); if(!isWithin(root,lexicalTarget)) throw new Error("Feature destination escapes the selected project");
    const included=built.config.artifacts.include.some(pattern=>new Bun.Glob(pattern).match(path)); const excluded=built.config.artifacts.exclude?.some(pattern=>new Bun.Glob(pattern).match(path));
    if(!included||excluded) throw new Error(`Feature destination is outside configured artifact scope: ${path}`);
    if(await Bun.file(lexicalTarget).exists()) throw new Error(`Feature destination already exists: ${path}`);
    const featureId=input.featureId?.trim()||`F-${fingerprint({idea:input.idea,title:input.title}).slice(0,8).toUpperCase()}`;
    if(built.graph.getEntity(featureId)) throw new Error(`Entity ${featureId} already exists`);
    const lexicalParent=dirname(lexicalTarget);let existingParent=lexicalParent;let canonicalExisting:string;for(;;){try{canonicalExisting=await realpath(existingParent);break;}catch{const parent=dirname(existingParent);if(parent===existingParent)throw new Error("Feature destination has no accessible repository parent");existingParent=parent;}}if(canonicalExisting!==root&&!isWithin(root,canonicalExisting))throw new Error("Feature destination resolves outside the selected project");await mkdir(lexicalParent,{recursive:true});const canonicalParent=await realpath(lexicalParent);if(canonicalParent!==root&&!isWithin(root,canonicalParent))throw new Error("Feature destination resolves outside the selected project");const target=resolve(canonicalParent,basename(lexicalTarget));if(!isWithin(root,target))throw new Error("Feature destination resolves outside the selected project");
    const content=path.endsWith(".md") ? `---\nlengthwise: 1\nid: ${JSON.stringify(featureId)}\ntype: feature\ntitle: ${JSON.stringify(input.title)}\nlifecycle: draft\nsignificance: ${input.significance??"M"}\n---\n\n${input.idea.trim()}\n` : `lengthwise: 1\nentities:\n  - id: ${JSON.stringify(featureId)}\n    type: feature\n    title: ${JSON.stringify(input.title)}\n    lifecycle: draft\n    significance: ${input.significance??"M"}\n    body: ${JSON.stringify(input.idea.trim())}\n`;
    await Bun.write(target,content);
    const rebuilt=await buildProjectGraph(this.repoRoot);
    if(!rebuilt.ok||!rebuilt.graph.getEntity(featureId)){try{await unlink(target);}catch{};throw new Error(`Created Feature artifact did not produce a valid Feature and was removed: ${rebuilt.diagnostics.map(d=>d.message).join("; ")}`);}
    const captured=this.state.start(featureId,"capture"); const assessment=await this.assess(featureId); this.state.event(captured.id,"feature-captured",{artifactPath:path,idea:input.idea},assessment.fingerprint,`${captured.id}:capture`); this.state.recordBaseline(captured.id,assessment.fingerprint,assessment); const run=this.state.update(captured.id,"specify","running"); return {run,assessment:await this.assess(featureId),artifactPath:path};
  }

  async assess(featureId: string): Promise<WorkflowAssessment> {
    const built = await buildProjectGraph(this.repoRoot);
    const emptyGates=()=>Object.fromEntries((["specification","build-contract","verification"] as WorkflowGate[]).map(g=>[g,{gate:g,required:false,eligible:false,approved:false,fingerprint:"invalid",blockers:[blocker("repository-invalid","Repository cannot currently build")]}])) as Record<WorkflowGate,GateAssessment>;
    if (!built.ok) return {featureId,repositoryValid:false,diagnostics:built.diagnostics,featureDiagnostics:built.diagnostics,blockingQuestions:[],tasks:[],verifications:[],gates:emptyGates(),actions:[],governingChanges:[],implementation:{attempts:[],pendingReturns:[],retryContexts:[]},reconciliation:{required:true,reasons:[blocker("repository-invalid","Repair repository artifacts before progression")]},specificationEligible:false,buildContractEligible:false,completionEligible:false,fingerprint:"invalid"};
    const feature = built.graph.getEntity(featureId); if (!feature || feature.type !== "feature") throw new Error(`Unknown feature ${featureId}`);
    const graph=built.graph; const diagnostics=runChecks(graph,built.config); const requirements=graph.outgoingRelationships(featureId).filter(r=>r.type==="addresses").map(r=>r.to);
    const criteria=requirements.flatMap(id=>graph.outgoingRelationships(id).filter(r=>r.type==="has-acceptance-criterion").map(r=>r.to));
    const taskEntities=graph.entitiesOfType("task").filter(t=>graph.outgoingRelationships(t.id).some(r=>r.type==="implements"&&requirements.includes(r.to)));
    const requiredVerifications=requiredVerificationsForFeature(graph,featureId); const scope=new Set([featureId,...requirements,...criteria,...taskEntities.map(t=>t.id),...requiredVerifications]);
    const questions=graph.outgoingRelationships(featureId).filter(r=>r.type==="has-question").map(r=>graph.getEntity(r.to)).filter(q=>q?.type==="question"); questions.forEach(q=>scope.add(q!.id));
    for(const id of [...scope]){for(const r of [...graph.incomingRelationships(id),...graph.outgoingRelationships(id)]) if(["contains","governs","contracts","includes","supports"].includes(r.type)){scope.add(r.from);scope.add(r.to);}}
    const scopedArtifacts=new Set([...scope].map(id=>graph.getEntity(id)?.source.artifactPath).filter(Boolean));
    const featureDiagnostics=diagnostics.filter(d=>d.entityId?scope.has(d.entityId):Boolean(d.location?.artifactPath&&scopedArtifacts.has(d.location.artifactPath)));
    const blockingQuestions=questions.filter(q=>q!.type==="question"&&q!.lifecycle==="open"&&q!.blocking).map(q=>q!.id);
    const tasks=taskEntities.map(t=>{const contract=graph.incomingRelationships(t.id).filter(r=>r.type==="contracts").map(r=>graph.getEntity(r.from)).find(e=>e?.type==="build-contract"&&e.lifecycle==="accepted");const stale=contract?.type==="build-contract"?contractStaleness(graph,contract.id):undefined;return {id:t.id,lifecycle:t.lifecycle,artifactPath:t.source.artifactPath,contract:contract?.id,contractArtifactPath:contract?.source.artifactPath,contractStale:stale?.stale,changedInputs:stale?.changedInputs??[],handoffEligible:Boolean(contract&&!stale?.stale&&t.lifecycle==="planned")};});
    const verifications=requiredVerifications.map(id=>{const v=graph.getEntity(id)!;const s=evidenceSatisfaction(graph,id);return {id,artifactPath:v.source.artifactPath,satisfied:s.satisfied,status:s.status,evidenceIds:s.evidence.map(e=>e.id),missingComplements:s.missingComplements};});
    const rigor=effectiveRigor(built.config,graph,featureId); const run=this.state.active(featureId)??this.state.latest(featureId);
    const specificationDiagnostics=featureDiagnostics.filter(d=>!["completeness/missing-implementation","completeness/missing-verification","graph/task-dependency-cycle"].includes(d.code));
    const common:WorkflowBlocker[]=[...specificationDiagnostics.filter(d=>d.severity==="error").map(d=>blocker(d.code,d.message,d.entityId,d.location?.artifactPath)),...blockingQuestions.map(id=>blocker("blocking-question",`Resolve blocking Question ${id} and propagate its answer`,id,graph.getEntity(id)?.source.artifactPath))];
    if(run&&!['cancelled','complete'].includes(run.state)&&!["verify","complete"].includes(run.activity)&&feature.lifecycle==="complete")common.unshift(blocker("lifecycle-run-conflict",`${featureId} is complete but has an active ${run.activity} workflow run`,featureId,feature.source.artifactPath));
    for(const q of questions.filter(q=>q!.type==="question"&&q!.lifecycle==="answered"&&!graph.outgoingRelationships(q!.id).some(r=>r.type==="resolved-by")))common.push(blocker("answer-not-propagated",`${q!.id} is answered but has no resolved-by link to updated governing context`,q!.id,q!.source.artifactPath));
    if(requirements.length===0) common.push(blocker("missing-requirements","Feature addresses no Requirement or NFR",featureId,feature.source.artifactPath));
    const specificationScope=new Set([featureId,...requirements,...criteria]);const specificationDecisions=graph.entitiesOfType("decision").filter(d=>graph.outgoingRelationships(d.id).some(r=>r.type==="governs"&&specificationScope.has(r.to))).map(d=>d.id).sort();
    const specificationInputs=[featureId,...requirements.sort(),...criteria.sort(),...specificationDecisions].map(id=>[id,gateSemanticFingerprint(graph.getEntity(id))]);
    const specFp=fingerprint({featureId,inputs:specificationInputs,blockers:common}); const specApproved=Boolean(run&&this.state.hasFreshEvent(run.id,"specification-approved",specFp));
    const planBlockers=[...common,...featureDiagnostics.filter(d=>d.severity==="error"&&!specificationDiagnostics.includes(d)).map(d=>blocker(d.code,d.message,d.entityId,d.location?.artifactPath))];
    const plans=graph.entitiesOfType("plan").filter(p=>graph.outgoingRelationships(p.id).some(r=>r.type==="contains"&&taskEntities.some(t=>t.id===r.to)));
    if(rigor.taskPlan==="required"&&(tasks.length===0||plans.length===0)) planBlockers.push(blocker("missing-task-plan","Effective rigor requires a Plan containing the Feature's implementation tasks",featureId,feature.source.artifactPath));
    for(const t of tasks){if(!t.contract)planBlockers.push(blocker("missing-contract",`${t.id} needs an accepted BuildContract`,t.id,t.artifactPath));else if(t.contractStale)planBlockers.push(blocker("stale-contract",`${t.contract} is stale: ${t.changedInputs.map(i=>i.id).join(", ")}`,t.contract,graph.getEntity(t.contract)?.source.artifactPath));}
    const contractFp=fingerprint({specFp,tasks:tasks.map(t=>({id:t.id,contract:t.contract,stale:t.contractStale,changed:t.changedInputs}))}); const contractApproved=Boolean(run&&this.state.hasFreshEvent(run.id,"build-contract-approved",contractFp));
    const verificationBlockers=verifications.filter(v=>!v.satisfied).map(v=>blocker(`evidence-${v.status}`,`${v.id} evidence is ${v.status}${v.missingComplements.length?`; missing ${v.missingComplements.join(", ")}`:""}`,v.id,v.artifactPath));
    const verificationFp=fingerprint({contractFp,verifications}); const verificationApproved=Boolean(run&&this.state.hasFreshEvent(run.id,"verification-approved",verificationFp));
    const requiredGates=new Set(rigor.humanApproval.map(g=>g==="buildContract"?"build-contract":g) as WorkflowGate[]);
    const gates:Record<WorkflowGate,GateAssessment>={
      specification:{gate:"specification",required:requiredGates.has("specification"),eligible:common.length===0,approved:specApproved,fingerprint:specFp,blockers:common},
      "build-contract":{gate:"build-contract",required:requiredGates.has("build-contract"),eligible:planBlockers.length===0&&(!requiredGates.has("specification")||specApproved),approved:contractApproved,fingerprint:contractFp,blockers:[...planBlockers,...(!specApproved&&requiredGates.has("specification")?[blocker("gate-order","Approve the current specification gate first")]:[])]},
      verification:{gate:"verification",required:requiredGates.has("verification"),eligible:verificationBlockers.length===0&&tasks.every(t=>graph.getEntity(t.id)?.lifecycle==="done")&&(!requiredGates.has("build-contract")||contractApproved),approved:verificationApproved,fingerprint:verificationFp,blockers:[...verificationBlockers,...tasks.filter(t=>graph.getEntity(t.id)?.lifecycle!=="done").map(t=>blocker("task-not-done",`${t.id} lifecycle is not done`,t.id,t.artifactPath)),...(!contractApproved&&requiredGates.has("build-contract")?[blocker("gate-order","Approve the current Build Contract gate first")]:[])]}
    };
    const events=run?this.state.events(run.id):[]; const implementation=implementationProjection(events);for(const returned of implementation.pendingReturns)returned.verificationIds=buildContractContext(graph,returned.taskId).verifications; const lastReconciledIndex=events.findLastIndex(e=>e.kind==="reconciliation-complete");
    for(const task of tasks){const retry=implementation.retryContexts.find(context=>context.taskId===task.id);if(retry&&!task.contractStale)task.handoffEligible=true;}
    const explicitReconciliation=events.slice(lastReconciledIndex+1).filter(e=>e.kind==="verification-reconciliation-required").map(e=>{const value=eventPayload<{taskId?:string;reason:string}>(e);return blocker("governing-context-conflict",value.reason,value.taskId);});
    const reconciliationReasons=[...tasks.filter(t=>t.contractStale).map(t=>blocker("contract-diverged",`${t.contract} no longer matches governing inputs`,t.contract)),...explicitReconciliation];
    const implementationBlockers=[...implementation.pendingReturns.map(value=>blocker("implementation-return-pending-verification",`${value.taskId} implementation completion claim has not been evaluated by verification`,value.taskId)),...implementation.retryContexts.map(value=>blocker("implementation-retry-pending",`${value.taskId} has unsatisfied implementation obligations awaiting another attempt`,value.taskId))];
    const completionBlockers=[...common,...planBlockers.filter(b=>!common.includes(b)),...verificationBlockers,...tasks.filter(t=>graph.getEntity(t.id)?.lifecycle!=="done").map(t=>blocker("task-not-done",`${t.id} lifecycle is not done`,t.id,t.artifactPath)),...implementationBlockers,...reconciliationReasons];
    for(const gate of Object.values(gates))if(gate.required&&!gate.approved)completionBlockers.push(blocker("approval-missing",`Current ${gate.gate} approval is required`));
    const completionEligible=completionBlockers.length===0; const overall=fingerprint({featureId,specFp,contractFp,verificationFp,completionEligible});
    const actions=this.actionsFor({featureId,featurePath:feature.source.artifactPath,featureLifecycle:feature.lifecycle,tasks,verifications,gates,completionEligible,reconciliationReasons,implementation,run});
    return {featureId,repositoryValid:true,diagnostics,featureDiagnostics,blockingQuestions,tasks,verifications,gates,actions,governingChanges:tasks.filter(t=>t.changedInputs.length).map(t=>({contractId:t.contract!,inputs:t.changedInputs})),implementation,reconciliation:{required:reconciliationReasons.length>0,reasons:reconciliationReasons,baselineFingerprint:run?this.state.latestBaseline(run.id)?.fingerprint:undefined},specificationEligible:gates.specification.eligible,buildContractEligible:gates["build-contract"].eligible,completionEligible,fingerprint:overall};
  }

  private actionsFor(input:{featureId:string;featurePath:string;featureLifecycle:string;tasks:WorkflowAssessment["tasks"];verifications:WorkflowAssessment["verifications"];gates:WorkflowAssessment["gates"];completionEligible:boolean;reconciliationReasons:WorkflowBlocker[];implementation:WorkflowAssessment["implementation"];run?:WorkflowRun}):WorkflowAction[]{
    const actions:WorkflowAction[]=[]; const add=(action:WorkflowAction)=>actions.push(action);
    if(input.run?.state==="complete"&&input.featureLifecycle==="complete")return actions;
    if(input.run&&!['cancelled','complete'].includes(input.run.state)&&input.run.activity!=="complete"&&input.featureLifecycle==="complete"&&!(input.run.activity==="verify"&&input.completionEligible))return [
      {id:"reopen-feature",kind:"author",label:`Reopen ${input.featureId} and continue`,eligible:true,requiredInputs:["Human decision that additional Feature work is intended"],expectedOutputs:["Feature lifecycle active","Existing workflow run retained"],target:{entityId:input.featureId,artifactPath:input.featurePath},blockers:[]},
      {id:"cancel-stale-run",kind:"cancel",label:`Keep ${input.featureId} complete and close the run`,eligible:true,requiredInputs:["Human decision that the Feature remains complete"],expectedOutputs:["Workflow run cancelled and retained in history"],target:{entityId:input.featureId,artifactPath:input.featurePath},blockers:[]},
    ];
    const specificationBlocker=input.gates.specification.blockers[0];
    if(!input.gates.specification.approved&&!input.gates.specification.eligible&&specificationBlocker){const label=specificationBlocker.code==="missing-requirements"?`Add a Requirement or NFR to ${input.featureId}`:specificationBlocker.code.includes("relationship")?`Repair ${specificationBlocker.entityId??input.featureId}'s relationship`:`Resolve ${specificationBlocker.entityId??"the specification blocker"}`;add({id:"repair-specification",kind:"author",label,eligible:true,requiredInputs:[specificationBlocker.message],expectedOutputs:["The blocking condition is resolved in the authoritative artifact"],target:{entityId:specificationBlocker.entityId??input.featureId,artifactPath:specificationBlocker.artifactPath??input.featurePath},blockers:[]});}
    if(!input.gates.specification.approved)add({id:"review-specification",kind:"gate-review",label:"Review and approve the specification",eligible:input.gates.specification.eligible,requiredInputs:["Current Feature, requirements, criteria, decisions, Questions, and findings"],expectedOutputs:["Reviewed authoritative lifecycle saves","Specification gate event"],target:{entityId:input.featureId,artifactPath:input.featurePath},blockers:input.gates.specification.blockers});
    if(input.gates.specification.approved&&!input.gates["build-contract"].approved)for(const task of input.tasks.filter(task=>!task.contract||task.contractStale))add({id:`author-contract:${task.id}`,kind:"author",label:task.contract?`Refresh ${task.contract}`:`Author BuildContract for ${task.id}`,eligible:true,requiredInputs:["Accepted specification","Task DAG","Verification topology","Accepted decision-authority metadata"],expectedOutputs:["Accepted machine-readable BuildContract"],target:{entityId:task.contract??task.id,entityType:"build-contract",artifactPath:task.contract?undefined:task.artifactPath.replace(/[^/]+$/,"contracts.yaml")},blockers:[]});
    if(input.gates["build-contract"].eligible&&!input.gates["build-contract"].approved){const reviewTarget=input.tasks.find(task=>task.contract&&task.contractArtifactPath);add({id:"review-build-contract",kind:"gate-review",label:"Review and approve Build Contracts",eligible:true,requiredInputs:["Current accepted BuildContracts and governing changes"],expectedOutputs:["Build Contract gate event"],target:{entityId:reviewTarget?.contract??input.featureId,artifactPath:reviewTarget?.contractArtifactPath??input.featurePath},blockers:[]});}
    if(input.run?.activity==="implement"&&(input.gates["build-contract"].approved||!input.gates["build-contract"].required)){const waiting=new Set(this.state.waiting(input.run.id,"implementation").map(wait=>wait.targetId));for(const task of input.tasks.filter(task=>!waiting.has(task.id)&&(task.lifecycle!=="done"||input.implementation.retryContexts.some(context=>context.taskId===task.id)))){const retry=input.implementation.retryContexts.find(context=>context.taskId===task.id);add({id:`handoff:${task.id}`,kind:"handoff",label:retry?`Retry implementation for ${task.id}`:`Hand off ${task.id} for implementation`,eligible:task.handoffEligible,requiredInputs:retry?[`Current accepted BuildContract ${retry.contractId??task.contract??""}`.trim(),`Failed verification: ${retry.failedVerifications.join(", ")}`,`Affected acceptance criteria: ${retry.affectedAcceptanceCriteria.join(", ")||"not derivable"}`,`Affected requirements: ${retry.affectedRequirements.join(", ")||"not derivable"}`,...retry.blockingFindings,...retry.knownGaps]:[`Current accepted BuildContract ${task.contract??""}`.trim()],expectedOutputs:["Recorded implementation handoff","Workflow waits for an implementation return"],target:{entityId:task.contract??task.id,artifactPath:task.contractArtifactPath??task.artifactPath},blockers:task.contractStale?[blocker("stale-contract","Refresh the BuildContract before handoff",task.contract)]:!retry&&task.lifecycle!=="planned"?[blocker("task-not-planned",`${task.id} must be planned before handoff`,task.id,task.artifactPath)]:[]});}for(const task of input.tasks.filter(task=>waiting.has(task.id)))add({id:`return:${task.id}`,kind:"implementation-return",label:`Record implementation return for ${task.id}`,eligible:true,requiredInputs:["Structured implementer completion claim","Known gaps and changed files"],expectedOutputs:["Recorded implementation return claim","The task enters verification coordination"],target:{entityId:task.id,artifactPath:task.artifactPath},blockers:[]});}
    for(const returned of input.implementation.pendingReturns)add({id:`review-return:${returned.taskId}`,kind:"verification-route",label:`Evaluate implementation return for ${returned.taskId}`,eligible:input.run?.activity==="verify",requiredInputs:["Implementation completion claim","Current required verification and Evidence","Classify omissions separately from governing-context conflicts"],expectedOutputs:["Retry implementation, enter reconciliation, or record satisfactory verification"],target:{entityId:returned.taskId,artifactPath:input.tasks.find(task=>task.id===returned.taskId)?.artifactPath},blockers:[]});
    for(const verification of input.verifications.filter(v=>!v.satisfied))add({id:`record-evidence:${verification.id}`,kind:"author",label:`Record applicable Evidence for ${verification.id}`,eligible:true,requiredInputs:["Observed result and pass/fail outcome","Evidence source or provenance","Applicability to the current verification context fingerprint or revision","Any complementary Evidence required by the Verification"],expectedOutputs:[`Recorded Evidence entity with a supports relationship to ${verification.id}`,"Evidence that is current, applicable, and sufficient for the Verification"],target:{entityId:verification.id,entityType:"evidence",artifactPath:verification.artifactPath},blockers:[]});
    if(input.reconciliationReasons.length)add({id:"reconcile",kind:"reconcile",label:"Reconcile implementation, contracts, Evidence, and governing artifacts",eligible:true,requiredInputs:["Implementation return claims","Current artifacts and checks","Evidence applicability","Governing changes"],expectedOutputs:["Updated authoritative artifacts or a converged reconciliation baseline"],target:{entityId:input.featureId,artifactPath:input.featurePath},blockers:input.reconciliationReasons});
    if(input.gates.verification.required&&input.gates.verification.eligible&&!input.gates.verification.approved){const reviewTarget=input.verifications[0];add({id:"review-verification",kind:"gate-review",label:"Review final verification evidence",eligible:true,requiredInputs:["Current applicable Evidence and reconciliation result"],expectedOutputs:["Verification gate event"],target:{entityId:reviewTarget?.id??input.featureId,artifactPath:reviewTarget?.artifactPath??input.featurePath},blockers:[]});}
    add({id:"complete-feature",kind:"author",label:"Save Feature lifecycle as complete",eligible:input.completionEligible,requiredInputs:["All deterministic completion obligations and required approvals"],expectedOutputs:["Feature lifecycle complete in its authoritative artifact","Terminal workflow run"],target:{entityId:input.featureId,artifactPath:input.featurePath},blockers:input.completionEligible?[]:[blocker("completion-ineligible","Resolve the listed workflow blockers first")]});
    return actions;
  }

  async approve(runId:string, gate:WorkflowGate, reviewedFingerprint:string, lifecycleEffects:Array<{entityId:string;from:string;to:string}>=[]) {
    const run=this.requireRun(runId); const assessment=await this.assess(run.featureId); const current=assessment.gates[gate];
    if(current.approved)return run;
    const allowed:Record<WorkflowGate,WorkflowActivity[]>={specification:["specify","reconcile"],"build-contract":["plan","reconcile"],verification:["verify","reconcile"]};if(!allowed[gate].includes(run.activity))throw new Error(`Cannot approve ${gate} gate during ${run.activity} activity`);
    if(current.fingerprint!==reviewedFingerprint)throw new Error(`Reviewed ${gate} context is stale; reload the current gate assessment`); if(!current.eligible)throw new Error(`${gate} gate is ineligible: ${current.blockers.map(b=>b.message).join("; ")}`);
    const built=await buildProjectGraph(this.repoRoot); if(!built.ok)throw new Error("Repository cannot currently build");
    for(const effect of lifecycleEffects){const entity=built.graph.getEntity(effect.entityId);if(!entity)throw new Error(`Reviewed lifecycle effect references unknown entity ${effect.entityId}`);if(entity.lifecycle!==effect.to)throw new Error(`Apply and save reviewed lifecycle effect ${effect.entityId}: ${effect.from} -> ${effect.to} before approval`);}
    const order:Record<WorkflowGate,WorkflowActivity>={specification:"plan","build-contract":"implement",verification:"reconcile"};
    this.state.event(runId,`${gate}-approved`,{lifecycleEffects},reviewedFingerprint,`${runId}:${gate}:${reviewedFingerprint}`); return this.state.update(runId,order[gate],gate==="build-contract"?"running":"running");
  }
  async handoff(runId:string,taskId:string,idempotencyKey:string){const run=this.requireRun(runId);const prior=this.state.attemptByKey(runId,`handoff:${taskId}`,idempotencyKey);if(prior)return prior;if(run.activity!=="implement")throw new Error(`Cannot hand off implementation during ${run.activity} activity`);const a=await this.assess(run.featureId);const task=a.tasks.find(t=>t.id===taskId);if(!task?.handoffEligible||(a.gates["build-contract"].required&&!a.gates["build-contract"].approved))throw new Error(`${taskId} is not eligible for handoff`);const attempt=this.state.beginAttempt(runId,`handoff:${taskId}`,idempotencyKey,a.fingerprint);const implementationAttemptId=crypto.randomUUID();const attemptNumber=a.implementation.attempts.filter(item=>item.taskId===taskId).length+1;const retryContext=a.implementation.retryContexts.find(context=>context.taskId===taskId);this.state.event(runId,"implementation-handed-off",{taskId,contractId:task.contract,implementationAttemptId,attemptNumber,...(retryContext?{retryContext}:{})},a.fingerprint,`${runId}:handoff:${taskId}:${idempotencyKey}`);this.state.wait(runId,"implementation",taskId);this.state.update(runId,"implement","waiting-implementation");return this.state.finishAttempt(attempt.id,"succeeded",{taskId,contractId:task.contract,implementationAttemptId,attemptNumber,retryContext});}
  async returnImplementation(runId:string,taskId:string,claim:ImplementationCompletionClaim|string,idempotencyKey:string){const run=this.requireRun(runId);const prior=this.state.attemptByKey(runId,`implementation-return:${taskId}`,idempotencyKey);if(prior)return prior;const events=this.state.events(runId);const returnedAttemptIds=new Set(events.filter(candidate=>candidate.kind==="implementation-returned").map(candidate=>eventPayload<{implementationAttemptId?:string}>(candidate).implementationAttemptId).filter(Boolean));const handoff=[...events].reverse().find(e=>e.kind==="implementation-handed-off"&&eventPayload<{taskId?:string}>(e).taskId===taskId&&!returnedAttemptIds.has(eventPayload<{implementationAttemptId?:string}>(e).implementationAttemptId??e.id));if(!handoff||!this.state.waiting(runId,"implementation").some(wait=>wait.targetId===taskId))throw new Error(`${taskId} has no outstanding implementation handoff`);const normalized:ImplementationCompletionClaim=typeof claim==="string"?{summary:claim}:claim;if(!normalized.summary?.trim()&&!normalized.claims&&!normalized.knownGaps?.length&&!normalized.changedFiles?.length)throw new Error("Implementation return requires a completion claim");const a=await this.assess(run.featureId);const attempt=this.state.beginAttempt(runId,`implementation-return:${taskId}`,idempotencyKey,a.fingerprint);const implementationAttemptId=eventPayload<{implementationAttemptId?:string}>(handoff).implementationAttemptId??handoff.id;this.state.event(runId,"implementation-returned",{taskId,implementationAttemptId,claim:normalized},a.fingerprint,`${runId}:return:${taskId}:${idempotencyKey}`);this.state.resolveWaits(runId,"implementation",taskId);const remaining=this.state.waiting(runId,"implementation");this.state.update(runId,remaining.length?"implement":"verify",remaining.length?"waiting-implementation":"running");return this.state.finishAttempt(attempt.id,"succeeded",{taskId,implementationAttemptId,claim:normalized,remaining:remaining.map(wait=>wait.targetId)});}
  async evaluateImplementationReturn(runId:string,input:{taskId:string;outcome:"retry-implementation"|"reconcile"|"satisfactory";failedVerifications?:string[];blockingFindings?:string[];knownGaps?:string[];reason?:string;idempotencyKey:string}){const run=this.requireRun(runId);const prior=this.state.attempts(runId).find(item=>item.idempotencyKey===input.idempotencyKey&&item.actionId.startsWith("evaluate-return:"));if(prior)return prior;if(run.activity!=="verify")throw new Error(`Cannot evaluate an implementation return during ${run.activity} activity`);const a=await this.assess(run.featureId);const returned=a.implementation.pendingReturns.find(value=>value.taskId===input.taskId);if(!returned)throw new Error(`${input.taskId} has no implementation return awaiting verification`);const task=a.tasks.find(value=>value.id===input.taskId);if(!task)throw new Error(`Unknown workflow task ${input.taskId}`);const built=await buildProjectGraph(this.repoRoot);if(!built.ok)throw new Error("Repository cannot currently build");
    if(input.outcome==="retry-implementation"){if(task.contractStale)throw new Error(`${task.contract} is stale; route governing-context changes to reconciliation`);const relevant=new Set(buildContractContext(built.graph,input.taskId).verifications);const failed=[...new Set(input.failedVerifications??a.verifications.filter(value=>relevant.has(value.id)&&!value.satisfied).map(value=>value.id))].sort();if(!failed.length)throw new Error("Retry routing requires at least one failed or missing verification obligation");if(failed.some(id=>!relevant.has(id)))throw new Error("Retry routing includes a verification outside the task's accepted Build Contract");const affected=affectedObligations(built.graph,input.taskId,failed);const retryContext:ImplementationRetryContext={taskId:input.taskId,implementationAttemptId:returned.implementationAttemptId,failedVerifications:failed,affectedAcceptanceCriteria:affected.acceptanceCriteria,affectedRequirements:affected.requirements,blockingFindings:input.blockingFindings??[],knownGaps:[...new Set([...(returned.claim.knownGaps??[]),...(input.knownGaps??[])])],contractId:task.contract,contractCurrent:true,nextEligibleAction:"implementation-handoff"};const attempt=this.state.beginAttempt(runId,`evaluate-return:${returned.implementationAttemptId}`,input.idempotencyKey,a.fingerprint);this.state.event(runId,"verification-returned-to-implementation",retryContext,a.fingerprint,`${runId}:verification-retry:${returned.implementationAttemptId}:${input.idempotencyKey}`);this.state.update(runId,"implement","running");return this.state.finishAttempt(attempt.id,"succeeded",retryContext);}
    if(input.outcome==="reconcile"){if(!input.reason?.trim())throw new Error("Reconciliation routing requires the governing-context conflict");const result={taskId:input.taskId,implementationAttemptId:returned.implementationAttemptId,reason:input.reason,failedVerifications:input.failedVerifications??[],blockingFindings:input.blockingFindings??[]};const attempt=this.state.beginAttempt(runId,`evaluate-return:${returned.implementationAttemptId}`,input.idempotencyKey,a.fingerprint);this.state.event(runId,"verification-reconciliation-required",result,a.fingerprint,`${runId}:verification-reconcile:${returned.implementationAttemptId}:${input.idempotencyKey}`);this.state.update(runId,"reconcile","running");return this.state.finishAttempt(attempt.id,"succeeded",result);}
    const context=buildContractContext(built.graph,input.taskId);const unsatisfied=a.verifications.filter(value=>context.verifications.includes(value.id)&&!value.satisfied);if(task.lifecycle!=="done"||unsatisfied.length)throw new Error(`Verification is not satisfactory for ${input.taskId}: ${[...(task.lifecycle!=="done"?["task lifecycle is not done"]:[]),...unsatisfied.map(value=>`${value.id} is ${value.status}`)].join("; ")}`);const result={taskId:input.taskId,implementationAttemptId:returned.implementationAttemptId,verified:context.verifications};const attempt=this.state.beginAttempt(runId,`evaluate-return:${returned.implementationAttemptId}`,input.idempotencyKey,a.fingerprint);this.state.event(runId,"implementation-verification-satisfactory",result,a.fingerprint,`${runId}:verification-satisfactory:${returned.implementationAttemptId}:${input.idempotencyKey}`);return this.state.finishAttempt(attempt.id,"succeeded",result);
  }
  interrupt(runId:string,reason:string){const run=this.requireRun(runId);for(const attempt of this.state.attempts(runId).filter(a=>a.state==="running"))this.state.finishAttempt(attempt.id,"interrupted",{reason});this.state.event(runId,"run-interrupted",{reason});return this.state.update(runId,run.activity,"interrupted");}
  async resume(runId:string){const run=this.requireRun(runId);const a=await this.assess(run.featureId);const interrupted=this.state.attempts(runId).filter(x=>x.state==="interrupted");const classifications=interrupted.map(x=>({attemptId:x.id,classification:x.repositoryFingerprint===a.fingerprint?"no-write-observed":"repository-changed-reconciliation-required"}));if(classifications.some(x=>x.classification.includes("reconciliation")))this.state.update(runId,"reconcile","running");else this.state.update(runId,run.activity,"running");this.state.event(runId,"run-resumed",{classifications},a.fingerprint);return {run:this.state.get(runId)!,assessment:await this.assess(run.featureId),classifications};}
  async retry(runId:string,attemptId:string){const run=this.requireRun(runId);const attempt=this.state.attempts(runId).find(a=>a.id===attemptId);if(!attempt)throw new Error(`Unknown attempt ${attemptId} for run ${runId}`);if(attempt.state==="succeeded")return attempt;const assessment=await this.assess(run.featureId);if(attempt.repositoryFingerprint!==assessment.fingerprint){this.state.update(runId,"reconcile","running");throw new Error("Repository changed since the interrupted action; reconcile before retrying");}const retried=this.state.retryAttempt(attemptId,assessment.fingerprint);this.state.event(runId,"action-retried",{attemptId,actionId:attempt.actionId},assessment.fingerprint,`${runId}:retry:${attemptId}:${assessment.fingerprint}`);return retried;}
  cancel(runId:string,reason:string){const run=this.requireRun(runId);this.state.event(runId,"run-cancelled",{reason});return this.state.update(runId,run.activity,"cancelled");}
  async reconcile(runId:string,route:Exclude<WorkflowActivity,"capture"|"complete">|"complete",reason:string,targetId?:string){const run=this.requireRun(runId);const a=await this.assess(run.featureId);const unresolved=a.reconciliation.reasons.filter(item=>item.code!=="governing-context-conflict");if(route==="complete"&&unresolved.length)throw new Error(`Reconciliation has not converged: ${unresolved.map(r=>r.message).join("; ")}`);if(run.activity!=="reconcile")this.state.update(runId,"reconcile","running");this.state.event(runId,route==="complete"?"reconciliation-complete":"reconciliation-directed",{route,reason,targetId},a.fingerprint);if(route==="complete")this.state.recordBaseline(runId,a.fingerprint,a);return this.state.update(runId,route==="complete"?"complete":route,"running");}
  async complete(runId:string){const run=this.requireRun(runId);const a=await this.assess(run.featureId);if(!a.completionEligible)throw new Error("Feature completion is not eligible");const built=await buildProjectGraph(this.repoRoot);if(!built.ok||built.graph.getEntity(run.featureId)?.lifecycle!=="complete")throw new Error("Save the Feature lifecycle as complete in its authoritative artifact before completing the run");this.state.event(runId,"workflow-completed",{},a.fingerprint,`${runId}:complete:${a.fingerprint}`);return this.state.update(runId,"complete","complete");}
  private requireRun(runId:string){const run=this.state.get(runId);if(!run)throw new Error(`Unknown workflow run ${runId}`);if(["cancelled","complete"].includes(run.state))throw new Error(`Workflow run ${runId} is terminal`);return run;}
  close(){this.state.close();}
}
